const domain: string =  'http://localhost:8000'//'http://f918bae6f5b0.ngrok.io'
export const authorizeUrl: string = domain + '/authorize'
export const authorizedUrl: string = domain + '/get_authorization_status'
export const userGearUrl: string = domain + '/user_gear'
export const athleteUrl: string = domain + '/athlete'
export const refreshBikesUrl: string = domain + '/refresh_athlete_bikes'
export const toggleGearTrackingUrl: string = domain + '/toggle_gear_tracking'
export const deleteGearUrl: string = domain + '/delete_gear'
export const addGearUrl: string = domain + '/add_gear'
export const addOrChangeGearUrl: string = domain + '/add_or_change_gear'
export const changeAthleteUrl: string = domain + '/change_athlete_field'

