# Generated by Django 3.0.9 on 2020-09-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_tracked', models.BooleanField()),
            ],
        ),
    ]
