# Generated by Django 3.0.9 on 2020-09-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20200904_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='mileage',
            field=models.FloatField(),
        ),
    ]
