# Generated by Django 3.0.9 on 2020-09-23 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20200917_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gear',
            name='user',
        ),
    ]
