# Generated by Django 3.0.9 on 2020-09-23 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_athlete'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='athlete',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.Athlete'),
        ),
    ]
