# Generated by Django 3.0.9 on 2020-09-23 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_gear_athlete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='ref',
            new_name='ref_id',
        ),
    ]
