# Generated by Django 3.0.9 on 2020-09-23 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20200923_0928'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gear',
            unique_together={('name', 'athlete')},
        ),
    ]
