# Generated by Django 3.0.9 on 2020-09-23 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20200923_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.IntegerField()),
                ('expires_in', models.IntegerField()),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('athlete', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.Athlete')),
            ],
        ),
    ]
