# Generated by Django 3.0.9 on 2020-09-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_tokendata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokendata',
            name='athlete',
        ),
    ]
