# Generated by Django 3.0.9 on 2020-09-24 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_remove_tokendata_athlete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Athlete')),
            ],
        ),
    ]
