# Generated by Django 3.0.9 on 2020-09-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_bike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='ref_id',
            field=models.CharField(max_length=255),
        ),
    ]
