# Generated by Django 3.0.9 on 2020-09-25 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_auto_20200924_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='bike',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.Bike'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='athlete',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.Athlete'),
        ),
    ]
