# Generated by Django 3.0.9 on 2020-10-04 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_auto_20200925_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='bike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.Bike'),
        ),
    ]
