# Generated by Django 3.0.9 on 2020-10-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_auto_20201004_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gear',
            name='bike',
        ),
        migrations.AddField(
            model_name='gear',
            name='bikes',
            field=models.ManyToManyField(to='tracker.Bike'),
        ),
    ]
