# Generated by Django 3.0.9 on 2020-10-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_auto_20201026_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gear',
            name='bike',
        ),
        migrations.AddField(
            model_name='gear',
            name='bike',
            field=models.ManyToManyField(to='tracker.Bike'),
        ),
    ]
