# Generated by Django 3.0.9 on 2020-10-26 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_auto_20201026_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gear',
            name='bike',
        ),
        migrations.AddField(
            model_name='gear',
            name='bike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.Bike'),
        ),
    ]
