# Generated by Django 3.0.9 on 2020-11-17 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_auto_20201110_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='elapsed_time',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='gear',
            name='moving_time',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
