# Generated by Django 3.0.9 on 2020-11-19 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0024_auto_20201119_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gear',
            old_name='mileage',
            new_name='distance',
        ),
    ]
