# Generated by Django 3.0.9 on 2020-11-23 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0026_auto_20201123_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gear',
            old_name='moving_time_milestone',
            new_name='_moving_time_milestone',
        ),
    ]
