# Generated by Django 3.0.9 on 2020-11-23 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0027_auto_20201123_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='athlete',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gear', to='tracker.Athlete'),
        ),
    ]
