# Generated by Django 3.0.9 on 2020-11-24 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0028_auto_20201123_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='distance_milestone',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
