# Generated by Django 3.0.9 on 2020-11-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0029_gear_distance_milestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='distance_unit',
            field=models.CharField(default='km', max_length=255),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='time_unit',
            field=models.CharField(default='mi', max_length=255),
        ),
    ]
