# Generated by Django 3.0.9 on 2020-11-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0032_auto_20201125_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='distance_unit',
            field=models.CharField(default='kilometer', max_length=255),
        ),
    ]
