# Generated by Django 3.0.9 on 2020-11-25 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0034_auto_20201125_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gear',
            old_name='distance',
            new_name='_distance',
        ),
    ]
