# Generated by Django 3.0.9 on 2020-11-25 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0035_auto_20201125_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gear',
            old_name='_distance',
            new_name='distance',
        ),
    ]
