# Generated by Django 3.0.9 on 2020-11-26 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0036_auto_20201125_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gear',
            old_name='_moving_time',
            new_name='moving_time',
        ),
        migrations.RenameField(
            model_name='gear',
            old_name='_moving_time_milestone',
            new_name='moving_time_milestone',
        ),
    ]
