# Generated by Django 3.0.9 on 2020-12-04 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0037_auto_20201126_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='time_unit',
        ),
        migrations.AlterField(
            model_name='bike',
            name='athlete',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bikes', to='tracker.Athlete'),
        ),
    ]
