# Generated by Django 3.0.9 on 2020-12-05 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0038_auto_20201204_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='athlete',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gear', to='tracker.Athlete'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='bikes',
            field=models.ManyToManyField(blank=True, null=True, to='tracker.Bike'),
        ),
    ]
