# Generated by Django 3.0.9 on 2020-12-05 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0039_auto_20201205_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='athlete',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gear', to='tracker.Athlete'),
        ),
        migrations.AlterField(
            model_name='gear',
            name='bikes',
            field=models.ManyToManyField(blank=True, to='tracker.Bike'),
        ),
    ]
