# Generated by Django 3.0.9 on 2020-12-08 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0041_remove_gear_elapsed_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokendata',
            name='athlete',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='tracker.Athlete'),
            preserve_default=False,
        ),
    ]
