# Generated by Django 3.0.9 on 2020-12-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0043_athlete_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='milestone_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
